# === backend-stack.yaml ===
AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue de backend Spring Boot en EC2

Parameters:
  KeyName:
    Type: String
    Description: Nombre del par de llaves EC2 existente
  JarS3Bucket:
    Type: String
    Description: Nombre del bucket S3 donde está el JAR
  JarFileName:
    Type: String
    Default: fondos-backend.jar

Resources:
  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite acceso al puerto 8080
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2
      SecurityGroups:
        - !Ref BackendSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install java-openjdk11 -y
          cd /home/ec2-user
          aws s3 cp s3://${JarS3Bucket}/${JarFileName} .
          java -jar ${JarFileName} > app.log 2>&1 &

Outputs:
  BackendInstancePublicIp:
    Description: IP pública de la instancia EC2
    Value: !GetAtt BackendInstance.PublicIp